### ISSUE TITLE
构建studio的时候shader 错误

### ISSUE THREAD

**Issue by windyslove** [JX-Master/Luna-Engine-0.6#1]
![image](https://user-images.githubusercontent.com/6903175/87227199-f2f2d780-c3cb-11ea-84a8-ad89e513936f.png)

**Comment by JX-Master** [comment]
您好。
这个问题是因为您没有正确设置编译的着色器参数导致的。
请在解决方案管理器中着色器文件上右键单击，打开属性，选择着色器类型，对于Pixel结尾的着色器文件，选择Pixel Shader；对于CS结尾的着色器文件，选择Compute Shader。着色模型统一选择SM5.0，应该就可以正常编译了。

**Comment by JX-Master** [comment]
已经在0.6.1中修复，现在shader编译配置直接写在CMakeLists.txt里，不需要手动指定了。
