### ISSUE TITLE
当我新建工程后遇到如下错误

### ISSUE THREAD

**Issue by hehhehee4** [JX-Master/Luna-Engine-0.6#2]
![企业微信截图_15988591347687](https://user-images.githubusercontent.com/62681919/91694480-2c132100-eb9f-11ea-818c-40a24bf8b426.png)

不知道是否跟我没有操作您如下语句有关系！
You may also need to copy the compiled shader files to `/Solution/` directory manually.

**Comment by PiangGG** [comment]
想知道怎么解决的，我也遇到了0.0

**Comment by JX-Master** [comment]
编译好的shader文件会有一堆.cso文件，要把这些.cso文件放在exe同级目录下。如果实在VS里面点击运行的，也要同时放在.vsproj文件同级目录下。

**Comment by JX-Master** [comment]
已经在0.6.1中修复，现在不需要手动拷贝文件了。
